### ISSUE TITLE
Code styling inside `style` tag don't same for `lang="postcss"` and default `css`

### ISSUE THREAD

**Issue by romanhrynevych** [volarjs/volar.js#170]
CSS: 
<img width="1043" alt="image" src="https://github.com/volarjs/volar.js/assets/82209198/7d175c72-5270-4092-b222-cd13b4a44a7e">

PostCSS:
<img width="1043" alt="image" src="https://github.com/volarjs/volar.js/assets/82209198/90aaf281-df7b-4351-ba1d-17c55f6a95e7">

Maybe this error don't relative to Volar, but maybe someone will help me with this)

**Comment by RayGuo-ergou** [comment]
It parsed to postcss and I guess there's no extension to support that in your IDE yet. Maybe this will help: https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss

Before:
![image](https://github.com/volarjs/volar.js/assets/33137074/27cb2ee0-5903-4cce-8cda-9e95420a6783)

After:
![image](https://github.com/volarjs/volar.js/assets/33137074/f196ed9a-abdd-4191-bd93-e7ff73fd3722)

**Comment by johnsoncodehk** [comment]
This is the expected behavior for CSS code blocks. It uses the built-in CSS syntax highlighting in VSCode. Since CSS itself does not support inline classes, you can see that `.animation-title` is not correctly colored.

For `lang="postcss"`, since VSCode does not have built-in PostCSS syntax highlighting, it will use the syntax highlighting provided by the PostCSS extension you have installed. The actual behavior depends on the PostCSS extension you have installed.
